### ISSUE TITLE
audio decoding error

### ISSUE THREAD

**Issue by dsaetgareev** [security-union/videocall-rs#139]
https://github.com/security-union/videocall-rs/blob/76c8d736e3349270950e7b2e439ccc643400da8a/yew-ui/src/model/decode/peer_decode_manager.rs#L107

Hello. I use part of the project code in my project, the code responsible for transferring the video and audio stream, I transfer chunks via webtrc. The video works without errors, while decoding the audio I get the error "Uncaught Error: closure invoked recursively or after being dropped". I've been struggling with this problem for three days now. Maybe you also faced this problem?
![Screenshot from 2023-08-31 21-02-41](https://github.com/security-union/videocall-rs/assets/25948215/497ba5b5-ec69-4667-8608-75c591b157b4)
![Screenshot from 2023-08-31 21-04-38](https://github.com/security-union/videocall-rs/assets/25948215/0a3ed5fb-b23a-4024-8611-fba5304d6bee)
![Screenshot from 2023-08-31 22-00-25](https://github.com/security-union/videocall-rs/assets/25948215/44e6d789-7ef9-4e1f-8378-d428c921e6d7)

**Comment by darioalessandro** [comment]
Hey @dsaetgareev indeed I have seen this!! 

this is likely because the `error` and `output` callbacks are being deallocated by rust but then javascript is trying to call them, to solve this simply call:

```
forget(error)
forget(output)
```

or store those callbacks such that they do not get dropped

**Comment by dsaetgareev** [comment]
Dario, hello!!! I just saw your message and immediately followed your advice, and everything worked!!! Added
 error.forget();
 output.forget();
Dario, thank you very much for your help!!
![image](https://github.com/security-union/videocall-rs/assets/25948215/34514846-35cb-4800-b2f6-099f23c7d600)

**Comment by darioalessandro** [comment]
that is awesome !!! 😄 glad I was able to help!
