### ISSUE TITLE
Feature: Handling connection errors on the UI

### ISSUE THREAD

**Issue by griffobeid** [security-union/videocall-rs#52]
**Is your feature request related to a problem? Please describe.**
The UI does not show when there are connection issues with the server. For example, if the server is not running it appears that the UI is able to connect to it when behind the scenes the connection is actually failing. 

**Describe the solution you'd like**
It would be nice to show the user that there is a problem connecting with the server somehow, then make the "close" button go back to the "connect" state.

**Comment by darioalessandro** [comment]
@griffobeid I think this is fixed?

**Comment by griffobeid** [comment]
Yes
